{
    "openapi": "3.0.0",
    "info": {
        "title": "PSF: Portugal Food Sustainability",
        "description": "API - Desenvolvimento sustentavel",
        "termsOfService": "http://localhost:5000/terms",
        "contact": {
            "name": "Developers - PDS 2022 - LESI",
            "url": "https://www.ipca.pt",
            "email": "codesolutions@gmail.com"
        },
        "license": {
            "name": "Use under IPCA rights",
            "url": "https://www.ipca.pt/license"
        },
        "version": "1.0.0"
    },
    "paths": {
        "/produto/publicarProduto": {
            "post": {
                "description": "Publicar um novo Produto",
                "tags": [
                    "Produtos"
                ],
                "operationId": "Produtos_publicarProduto",
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Produto"
                            },
                            "examples": {
                                "Produto": {
                                    "value": {
                                        "name": "oi",
                                        "image": "alo",
                                        "quantity": 333,
                                        "price": 23,
                                        "hourRecoMin": "10/10/10",
                                        "hourRecoMax": "10/10/12",
                                        "lojaId": 1,
                                        "subCatProdId": 1,
                                        "token": "eyJhbGciOiJIUzI1NiJ9.c2lsdmEucGFzdGVsYXJpYUBvdXRsb29rLmasasa asNvbQ.703UrqoZVtpVtqLjGILK05OrnNYUEnN_3URwkOjbymI"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "403": {
                        "description": "Forbidden!"
                    },
                    "404": {
                        "description": "Not found!"
                    },
                    "201": {
                        "description": "Created Post!"
                    }
                }
            }
        },
        "/produto/editarProduto": {
            "post": {
                "description": "Editar um Produto",
                "tags": [
                    "Produtos"
                ],
                "operationId": "Produtos_editarProduto",
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/EditarProduto"
                            },
                            "examples": {
                                "Produto": {
                                    "value": {
                                        "id": 1,
                                        "name": "oi",
                                        "image": "alo",
                                        "quantity": 333,
                                        "price": 23,
                                        "hourRecoMin": "10/10/10",
                                        "hourRecoMax": "10/10/12",
                                        "lojaId": 1,
                                        "subCatProdId": 1,
                                        "token": "eyJhbGciOiJIUzI1NiJ9.c2lsdmEucGFzdGVsYXJpYUBvdXRsb29rLmasasa asNvbQ.703UrqoZVtpVtqLjGILK05OrnNYUEnN_3URwkOjbymI"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "403": {
                        "description": "Forbidden!"
                    },
                    "404": {
                        "description": "Not Found!"
                    },
                    "201": {
                        "description": "Created Post!"
                    }
                }
            }
        },
        "/listarProdutos": {
            "post": {
                "description": "Listar Produtos",
                "tags": [
                    "Produtos"
                ],
                "operationId": "Produtos_listarProduto",
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/ListarProduto"
                            },
                            "examples": {
                                "Produto": {
                                    "value": {
                                        "token": "eyJhbGciOiJIUzI1NiJ9.am9hby5mZXJuYW5kZXNAY29kZXNvbHV0"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "403": {
                        "description": "Forbidden!"
                    },
                    "201": {
                        "description": "Created Post!",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/ListarProduto"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Efetuar Login",
                "tags": [
                    "Security"
                ],
                "operationId": "Security_login",
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Produto"
                            },
                            "examples": {
                                "Login": {
                                    "value": {
                                        "username": "name@example.pt",
                                        "password": "123456789"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "404": {
                        "description": "Not Found!"
                    },
                    "201": {
                        "description": "Created Post!",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Login"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/registeruser": {
            "post": {
                "description": "Efetuar um Registo",
                "tags": [
                    "Security"
                ],
                "operationId": "Security_registeruser",
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Registeruser"
                            },
                            "examples": {
                                "Cliente": {
                                    "value": {
                                        "name": "name example",
                                        "password": "123456789",
                                        "email": "name@example.pt",
                                        "contact": "name@example.pt",
                                        "nif": "123456789",
                                        "permission": "3"
                                    }
                                },
                                "Loja": {
                                    "value": {
                                        "name": "name example",
                                        "password": "123456789",
                                        "email": "name@example.pt",
                                        "contact": "name@example.pt",
                                        "nif": "123456789",
                                        "permission": "2"
                                    }
                                },
                                "Admin": {
                                    "value": {
                                        "name": "name example",
                                        "password": "123456789",
                                        "email": "name@example.pt",
                                        "contact": "name@example.pt",
                                        "nif": "123456789",
                                        "permission": "1"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Unauthorized!"
                    },
                    "201": {
                        "description": "Created Post!"
                    }
                }
            }
        },
        "/mostarPerfil": {
            "post": {
                "description": "Mostrar Perfil de um Utilizador",
                "tags": [
                    "Perfil"
                ],
                "operationId": "Security_mostarPerfil",
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/MostarPerfil"
                            },
                            "examples": {
                                "Utilizador": {
                                    "value": {
                                        "username": "nameexample@code.pt",
                                        "token": "eyJhbGciOiJIUzI1NiJ9.am9hby5mZXJuy5wdA.TEow1rNQRINYiToJ6rjybw"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "404": {
                        "description": "Not Found!"
                    },
                    "201": {
                        "description": "Created Post!"
                    }
                }
            }
        },
        "/candidaturaLoja": {
            "post": {
                "description": "Candidaturas das Lojas",
                "tags": [
                    "Candidaturas"
                ],
                "operationId": "Candidaturas_candidatura",
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "file": {
                                        "type": "string",
                                        "format": "binary"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "404": {
                        "description": "Not Found!"
                    },
                    "201": {
                        "description": "Created Post!"
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Login": {
                "type": "object",
                "properties": {
                    "token": {
                        "type": "string"
                    }
                }
            },
            "EditarProduto": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer"
                    },
                    "name": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "contact": {
                        "type": "integer"
                    },
                    "nif": {
                        "type": "integer"
                    },
                    "permisson": {
                        "type": "integer"
                    }
                }
            },
            "ListarProduto": {
                "type": "object",
                "properties": {
                    "idProduto": {
                        "type": "integer"
                    },
                    "nomeProduto": {
                        "type": "string"
                    },
                    "quantidade": {
                        "type": "integer"
                    },
                    "preco": {
                        "type": "number"
                    },
                    "horaRecolhaMin": {
                        "type": "string"
                    },
                    "horaRecolhaMax": {
                        "type": "string"
                    },
                    "fotoProduto": {
                        "type": "string"
                    },
                    "lojaId": {
                        "type": "integer"
                    },
                    "SubcategoriaProdId": {
                        "type": "integer"
                    }
                }
            },
            "MostarPerfil": {
                "type": "object",
                "properties": {
                    "nome": {
                        "type": "integer"
                    },
                    "email": {
                        "type": "number"
                    },
                    "contacto": {
                        "type": "string"
                    }
                }
            }
        }
    }
}